# This configuration creates one Source (GMod/TF2/etc.) game server instance. No ADS instances are created.
# If you intend to run more than one game server, use the ADS module instead.
version: "3"
services:
  amp:
    container_name: amp
    image: mitchtalmadge/amp-dockerized:latest
    mac_address: 02:42:AC:XX:XX:XX # Please see the README about this field.
    ports:
      - 27015:27015/udp # Notice how this is UDP, not TCP.
    volumes:
      - ./ampdata:/home/amp/.ampdata
    environment:
      - "UID=120" # Change according to which user on the host will own the ampdata volume.
      - "GID=124"
      - "LICENCE=#########-####-#####-##########"
      - "MODULE=srcds"
    restart: unless-stopped
