# This configuration creates one Minecraft instance. No ADS instances are created.
version: "3"
services:
  amp:
    container_name: amp
    image: mitchtalmadge/amp-dockerized:latest
    ports:
      - 25565:25565
      - 25570:8080
    volumes:
      - ./ampdata:/ampdata
    environment:
      - "UID=120" # Change according to which user on the host will own the ampdata volume.
      - "GID=124"
      - "LICENCE=#########-####-#####-##########"
      - "MODULE=Minecraft"
    restart: unless-stopped
