name: Auto Release

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # Every day at 2 PM MST (Releases tend to show up sometime around noon)

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get install -y --no-install-recommends wget jq

      - name: Download AMP Versions
        run: wget https://cubecoders.com/AMPVersions.json -O .github/workflows/data/AMPVersions.json

      - name: Parse Versions
        run: |
          echo "LATEST_RELEASE_VERSION=$(git tag -l --sort=-refname | grep '^[0-9]$' -m 1)" >> $GITHUB_ENV
          echo "AMP_CORE_VERSION=$(jq -r '.AMPCore' .github/workflows/data/AMPVersions.json | sed -e 's/\.//g')" >> $GITHUB_ENV
          echo "AMP_INST_MGR_VERSION=$(jq -r '.InstanceManagerCLI' .github/workflows/data/AMPVersions.json | sed -e 's/\.//g')" >> $GITHUB_ENV

      - name: Compare and Tag
        run: |
          git diff-index --quiet HEAD -- && { echo "Already up-to-date"; exit; }
          git --no-pager diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "Auto Update AMP Versions"
          git tag -a "$LATEST_RELEASE_VERSION-ampcore$AMP_CORE_VERSION-ampinstmgr$AMP_INST_MGR_VERSION" -m "Auto Release Latest AMP Version" 
          git push --follow-tags