name: "Auto Deploy Staging Branches"

on:
  push:
    branches:
      - "staging*"

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/heads/staging') }}
    uses: MitchTalmadge/AMP-dockerized/.github/workflows/build.yml@${{github.ref}}

  deploy:
    needs: [build]
    uses: MitchTalmadge/AMP-dockerized/.github/workflows/deploy-staging.yml@${{github.ref}}
