name: Build and Deploy

on: 
  create:
    tags:
      - "v[0-9]+-.+"
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Branch Name
        id: extract_branch
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - 
        name: Extract Tag Name
        id: extract_tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: echo "DEPLOY_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - 
        name: Get Latest Tag
        id: latest_tag
        if: ${{ github.event_name == "workflow_dispatch" }}
        shell: bash
        run: echo "DEPLOY_TAG=$(git tag -l --sort=-committerdate | grep -E '^v[0-9]+-.+$' -m 1)" >> $GITHUB_ENV
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: amp-dockerized:latest
      - 
        name: Tag Versions
        if: ${{ $DEPLOY_TAG != '' }}
        run: |
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:latest 
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:$DEPLOY_TAG
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:`echo $DEPLOY_TAG | sed -nE 's/^(v[0-9]+)-.+$/\1/p'`
      - 
        name: Tag Staging
        if: ${{ startsWith(steps.extract_branch.outputs.branch, 'staging') }}
        run: docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{steps.extract_branch.outputs.branch}}
      - 
        name: Count Tags
        id: count_tags
        run: echo "##[set-output name=tag_count;]$(echo `docker image ls mitchtalmadge/amp-dockerized -q | wc -l`)"
      -
        name: Login to Docker Hub
        if: ${{steps.count_tags.outputs.tag_count > 0}}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Push to Docker Hub
        if: ${{steps.count_tags.outputs.tag_count > 0}}
        run: docker image push --all-tags mitchtalmadge/amp-dockerized