name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     tags: amp-dockerized:latest
      - 
        name: Tag Staging
        if: ${{ startsWith(steps.extract_branch.branch, 'staging') }}
        run: docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{steps.extract_branch.branch}}
      - 
        name: Push to Docker Hub
        run: docker image push --all-tags mitchtalmadge/amp-dockerized