name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Branch Name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - 
        name: Extract Tag Name
        id: extract_tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: amp-dockerized:latest
      - 
        name: Tag Latest
        if: ${{ startsWith(steps.extract_tag.outputs.tag, 'v') }}
        run: docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:latest
      - 
        name: Tag Staging
        if: ${{ startsWith(steps.extract_branch.outputs.branch, 'staging') }}
        run: docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{steps.extract_branch.outputs.branch}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Push to Docker Hub
        run: docker image push --all-tags mitchtalmadge/amp-dockerized