name: "Build"

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/build.yml

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build Docker Image"
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          tags: amp-dockerized:latest
          outputs: type=docker,dest=/tmp/amp-dockerized-${{ matrix.arch }}.tar
      - name: "Upload Docker Image Artifact"
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/upload-artifact@v2
        with:
          name: image-${{ matrix.arch }}
          path: /tmp/amp-dockerized-${{ matrix.arch }}.tar
