name: "Check for Updates"

on:
  schedule:
    - cron: "0 * * * *" # Hourly
  workflow_dispatch:

jobs:
  get_latest_version:
    name: "Get Latest Version"
    runs-on: ubuntu-latest
    steps:
      - name: "Download AMP Versions"
        run: wget https://cubecoders.com/AMPVersions.json -O /tmp/AMPVersions.json
      - name: "Parse Versions"
        run: |
          echo "AMP_CORE_VERSION=$(jq -r '.AMPCore' /tmp/AMPVersions.json | sed -e 's/\.//g')" >> $GITHUB_ENV
          echo "AMP_INST_MGR_VERSION=$(jq -r '.InstanceManagerCLI' /tmp/AMPVersions.json | sed -e 's/\.//g')" >> $GITHUB_ENV

  get_latest_filesize:
    name: "Get Latest Filesize"
    runs-on: ubuntu-latest
    steps:
      - name: "Get Latest Filesize"
        run: echo "AMP_FILESIZE=$(curl https://cubecoders.com/Downloads/AMP_Latest.zip --head --silent | awk '$1 == "content-length:" {print $2}' | sed -e '/^$/d')" >> $GITHUB_ENV
