name: "Deploy Production"

on:
  workflow_call:
    inputs:
      git_release_version:
        required: true
        type: string
      amp_core_version:
        required: true
        type: string
      amp_instmgr_version:
        required: true
        type: string
      amp_last_modified:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Download Docker Image Artifacts"
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      - name: "Load Docker Image"
        run: |
          for f in $(find /tmp -type f -iname 'docker-image*.tar' -print); do
            docker load --input ${f}
          done
          docker image ls -a
      - name: "Tag Docker Images"
        run: |
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:latest 
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{inputs.git_release_version}} 
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{inputs.git_release_version}}-ampcore${{inputs.amp_core_version}}-ampinstmgr${{inputs.amp_instmgr_version}}
          docker tag amp-dockerized:latest mitchtalmadge/amp-dockerized:${{inputs.git_release_version}}-ampcore${{inputs.amp_core_version}}-ampinstmgr${{inputs.amp_instmgr_version}}-${{inputs.amp_last_modified}}
      - name: "Checkout Git Repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Commit Git Tag"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          TAG=${{inputs.git_release_version}}-ampcore${{inputs.amp_core_version}}-ampinstmgr${{inputs.amp_instmgr_version}}-${{inputs.amp_last_modified}}
          git tag -a "${TAG}" -m "Auto Release Latest AMP Version" || { echo "Tag already exists"; exit; }
          git push --follow-tags
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Deploy to Docker Hub"
        run: docker image push --all-tags mitchtalmadge/amp-dockerized
